name: Docker Octave images

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_octave:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [4, 5, 6, 7]
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: build-octave-${{ matrix.version }}.docker
          build-args: |
            OCTAVE_VERSION=${{ matrix.version }}
          push: true
          tags: gnuoctave/octave-build:${{ matrix.version }}
      - # copy multiplatform image from dockerhub to ghcr
        name: Push Image to multiple registries
        uses: akhilerm/tag-push-action@v2.0.0
        with:
          src: docker.io/gnuoctave/octave-build:${{ matrix.version }}
          dst: ghcr.io/gnu-octave/octave-build:${{ matrix.version }}


  octave:
    runs-on: ubuntu-latest
    needs: build_octave
    strategy:
      matrix:
        version:
        - 4.0.0
        - 4.0.1
        - 4.0.2
        - 4.0.3
        - 4.2.0
        - 4.2.1
        - 4.2.2
        - 4.4.0
        - 4.4.1
        - 5.1.0
        - 5.2.0
        - 6.1.0
        - 6.2.0
        - 6.3.0
        - 6.4.0
        - 7.1.0
        - 7.2.0
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Determine build image
        run: |
          VER=${{ matrix.version }}
          BUILD_VER=${VER%%.*}
          ## Exception, because of too old libraries.
          if [ "$VER" = "4.4.0" ] || [ "$VER" = "4.4.1" ]; then
            BUILD_VER=5
          fi
          echo "OCTAVE_BUILD_IMG=$BUILD_VER" >> $GITHUB_ENV
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: octave-${{ env.OCTAVE_BUILD_IMG }}.docker
          build-args: |
            OCTAVE_VERSION=${{ matrix.version }}
          push: true
          tags: gnuoctave/octave:${{ matrix.version }}
      - # copy multiplatform image from dockerhub to ghcr
        name: Push Image to multiple registries
        uses: akhilerm/tag-push-action@v2.0.0
        with:
          src: docker.io/gnuoctave/octave:${{ matrix.version }}
          dst: ghcr.io/gnu-octave/octave:${{ matrix.version }}


  jupyterlab:
    runs-on: ubuntu-latest
    needs: [build_octave, octave]
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: jupyterlab
          push: true
          tags: gnuoctave/octave:jupyterlab
      - # copy multiplatform image from dockerhub to ghcr
        name: Push Image to multiple registries
        uses: akhilerm/tag-push-action@v2.0.0
        with:
          src: docker.io/gnuoctave/octave:jupyterlab
          dst: ghcr.io/gnu-octave/octave:jupyterlab

